### ISSUE TITLE
Ensure reconnect cycle works

### ISSUE THREAD

**Issue by anarthal** [anarthal/mysql#24]
Ensure you can reconnect after a failed handshake/successful close.

**Comment by anarthal** [comment]
I don't think this is possible with asio sockets, as they have to be re-created once they are closed.

**Comment by madmongo1** [comment]
You can close and re-open an asio socket. Under the covers it’s just a socket descriptor.
What did you try?

**Comment by anarthal** [comment]
By bad, I was convinced of the opposite. There is actually a problem with the reconnect cycle, requires further investigation.

**Comment by anarthal** [comment]
Fixed in branch `reconnect-cycle` - will merge tomorrow after CI builds.
