### ISSUE TITLE
Is it stable?

### ISSUE THREAD

**Issue by SplitGemini** [anarthal/mysql#57]
I mean, fully tested, or fully available？

**Comment by anarthal** [comment]
Hi,

Yes, it is fully tested and fully available. But please bear in mind that the library hasn't been officially reviewed by the Boost community yet. This will happen between the 9th and the 18th of May this year. Depending on the outcome of the review, I may need to incorporate changes that may not be backwards compatible. If this is the case, this would be done in the form of a new 0.3.0 release (or similar).

For any other question, please let me know. Hope that helped.
